export { WebProjectTemplate } from './web'
export { AppProjectTemplate } from './app'
export { DesktopAppProjectTemplate } from './desktopApp'
export { ProductProjectTemplate } from './product'
export { BrandingProjectTemplate } from './branding'
export { MovieProjectTemplate } from './movie'
