export { default as Hero } from './hero'
export { default as CTA } from './cta'
export { default as Facts } from './facts'
export { default as FreeTime } from './freeTime'
export { default as Nav } from './components/nav'
