export * as Config from './config'
export { default as setConfig } from './config'
export { default as getInviewAnimationValue } from './getInviewAnimationValue'
export { default as framerDefaultTransitions } from './framerDefaultTransition'
export { PageTransition } from './pageTransition'
// export { SmoothScrollLegacy } from './smoothScroll.legacy'
export { SmoothScroll } from './smoothScroll'
