export const metadataData = {
  appName: 'TheIceJI Cosmos',
  title: 'TheIceJi | Where the dream begins',
  url: 'https://cosmos.theiceji.com',
  description:
    "I'm Jirayu Ninlapun (TheIceJi), a Creative Developer with a passion for pushing the boundaries of web technology. My expertise lies in WebGL, GLSL, and 3D development, and I thrive on creating immersive and visually stunning experiences. With a strong background in front-end development and NextJS, I excel at crafting engaging web animations that captivate users.",
  coverImg: '/og.jpg',
  author: 'Jirayu Ninlapun (TheIceJi)',
  keywords: [
    'TheIceJi',
    'Jirayu Ninlapun',
    'Web Developer',
    'Creative Developer',
    'NextJs Developer',
    'ThreeJs',
    'GLSL',
    'Professional',
    'DimensionsAI',
    'Artscape',
    'Graphics Designer',
    'VFX Artist',
    'Sound Engineer',
    'ไอซ์จิ',
    'จิรายุ นิลพันธุ์',
    'IceJiVerse',
    'Celestia',
    'Cosmos',
    'Nexus',
    'Web3',
    'Nebula',
    'Stella',
    'InterLink',
    'Astra',
  ],
  twitterID: '@theiceji',
}
