const Data = () => ({
  name: 'server',
  contents: [
    {
      isHeader: true,
      name: 'Aurora Backend',
      className: '',
    },
    {
      isHeader: false,
      name: 'NodeJs',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'GraphQL API',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'MongoDB Connection',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'PostgreSQL Connection',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'Redis Caching',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: true,
      name: 'Aurora Server',
      className: '',
    },
    {
      isHeader: false,
      name: 'AP-SouthEast-1 (Sydney)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AP-SouthEast-2 (Sydney)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'US-East-1 (Ashburn)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'US-East-2 (Ashburn)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'US-West-2 (Oregon)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'SEA-1 (Thailand)',
      value: 'slow',
      className: 'text-yellow-500',
    },
    {
      isHeader: false,
      name: 'SEA-2 (Singapore)',
      value: 'normal',
      className: 'text-green-500',
    },

    {
      isHeader: true,
      name: 'Aurora Nodes',
      className: '',
    },
    {
      isHeader: false,
      name: 'AM US-East-1 (N. Virginia)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AM EU-West-3 (Paris)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AM AP-NorthEast-2 (Seoul)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'PM US-East-1 (N. Virginia)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'PM AP-SouthEast-1 (Singapore)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AsM US-West-2 (Oregon)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AsM EU-Central-1 (Frankfurt)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AsM AP-NorthEast-1 (Japan)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AsM AP-NorthEast-2 (Seoul)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: true,
      name: 'SQL Servers',
      className: '',
    },
    {
      isHeader: false,
      name: 'AWS AP-southeast-1',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AWS US-East-1',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: true,
      name: 'Redis Servers',
      className: '',
    },
    {
      isHeader: false,
      name: 'AP-southeast-1',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'US-East-1',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: true,
      name: 'MongoDB Servers',
      className: '',
    },
    {
      isHeader: false,
      name: 'US-West-2 (Oregon)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'US-East-1 (N. Virginia)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'EU-West-3 (Paris)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'EU-Central-1 (Frankfurt)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AP-NorthEast-2 (Seoul)',
      value: 'normal',
      className: 'text-green-500',
    },
    {
      isHeader: false,
      name: 'AP-SouthEast-1 (Singapore)',
      value: 'stopped',
      className: 'text-orange-500',
    },
    {
      isHeader: false,
      name: 'AP-NorthEast-1 (Japan)',
      value: 'normal',
      className: 'text-green-500',
    },
  ],
})

export default Data
