export enum TYPE {
  APP = 'APP',
  DESKTOP_APP = 'DESKTOP_APP',
  WEB = 'WEB',
  PRODUCT = 'PRODUCT',
  MOVIE = 'MOVIE',
  BRANDING = 'BRANDING',
}

export enum HEADER {
  FULL = 'FULL',
  FULL_CENTER = 'FULL_CENTER',
  IMMERSIVE = 'IMMERSIVE',
  GALLERY = 'GALLERY',
  HALF = 'HALF',
  OVERLAP = 'OVERLAP',
}

export enum INFO_TYPE {
  INLINE_GRID = 'INLINE_GRID',
}

export enum INFO_APP_TARGET {
  DESKTOP = 'DESKTOP',
  MOBILE = 'MOBILE',
  CROSS_PLATFORM = 'CROSS_PLATFORM',
  WEB_APP = 'WEB_APP',
}

export enum BLOCK_TYPE {
  COLOR_PALETTE = 'COLOR_PALETTE',
  CONTENT = 'CONTENT',
  QUOTE = 'QUOTE',
  MARQUEE = 'MARQUEE',
  GRID = 'GRID',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}

export enum IMAGE {
  MOBILE_MOCKUP = 'MOBILE_MOCKUP',
  ONE_IMAGE = 'ONE_IMAGE',
  TWO_IMAGE = 'TWO_IMAGE',
  GALLERY_4 = 'GALLERY_4',
  BANNER = 'BANNER',
  BANNER_LOGO = 'BANNER_LOGO',
}

export enum COLOR_PALETTE {
  DEFAULT = 'DEFAULT',
  MINIMAL = 'MINIMAL',
  CARD = 'CARD',
}

export enum GRID {
  DEFAULT = 'DEFAULT',
  MINIMAL = 'MINIMAL',
  CARD = 'CARD',
}

export enum VIDEO_SRC {
  VIMEO = 'VIMEO',
  YOUTUBE = 'YOUTUBE',
}

export enum MARQUEE {
  AUTO = 'AUTO',
  SCROLLING = 'SCROLLING',
}
